/*
 Navicat Premium Data Transfer

 Source Server         : JuaraCoding
 Source Server Type    : PostgreSQL
 Source Server Version : 120022 (120022)
 Source Host           : localhost:5433
 Source Catalog        : wallet_db
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120022 (120022)
 File Encoding         : 65001

 Date: 23/01/2025 21:43:03
*/


-- ----------------------------
-- Sequence structure for mst_transaction_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."mst_transaction_id_seq";
CREATE SEQUENCE "public"."mst_transaction_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for mst_users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."mst_users_id_seq";
CREATE SEQUENCE "public"."mst_users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for mst_transaction
-- ----------------------------
DROP TABLE IF EXISTS "public"."mst_transaction";
CREATE TABLE "public"."mst_transaction" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "amount" numeric(15,2) NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "type" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "user_id" int8 NOT NULL
)
;

-- ----------------------------
-- Records of mst_transaction
-- ----------------------------
INSERT INTO "public"."mst_transaction" VALUES (1, 1000.00, '2025-01-23 21:17:49.653535', 'CREDIT', 1);
INSERT INTO "public"."mst_transaction" VALUES (2, 10.00, '2025-01-23 21:18:27.124813', 'DEBIT', 1);

-- ----------------------------
-- Table structure for mst_users
-- ----------------------------
DROP TABLE IF EXISTS "public"."mst_users";
CREATE TABLE "public"."mst_users" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "balance" numeric(15,2) NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of mst_users
-- ----------------------------
INSERT INTO "public"."mst_users" VALUES (1, 990.00, '2025-01-23 21:17:49.463527', 'Jefri');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."mst_transaction_id_seq"
OWNED BY "public"."mst_transaction"."id";
SELECT setval('"public"."mst_transaction_id_seq"', 2, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."mst_users_id_seq"
OWNED BY "public"."mst_users"."id";
SELECT setval('"public"."mst_users_id_seq"', 1, true);

-- ----------------------------
-- Auto increment value for mst_transaction
-- ----------------------------
SELECT setval('"public"."mst_transaction_id_seq"', 2, true);

-- ----------------------------
-- Checks structure for table mst_transaction
-- ----------------------------
ALTER TABLE "public"."mst_transaction" ADD CONSTRAINT "mst_transaction_type_check" CHECK (type::text = ANY (ARRAY['CREDIT'::character varying, 'DEBIT'::character varying]::text[]));

-- ----------------------------
-- Primary Key structure for table mst_transaction
-- ----------------------------
ALTER TABLE "public"."mst_transaction" ADD CONSTRAINT "mst_transaction_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for mst_users
-- ----------------------------
SELECT setval('"public"."mst_users_id_seq"', 1, true);

-- ----------------------------
-- Uniques structure for table mst_users
-- ----------------------------
ALTER TABLE "public"."mst_users" ADD CONSTRAINT "ukgsavt2jkxogr5trgpvuvunvr" UNIQUE ("username");

-- ----------------------------
-- Primary Key structure for table mst_users
-- ----------------------------
ALTER TABLE "public"."mst_users" ADD CONSTRAINT "mst_users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table mst_transaction
-- ----------------------------
ALTER TABLE "public"."mst_transaction" ADD CONSTRAINT "fk33xsck5868iwv7hvu5620u48f" FOREIGN KEY ("user_id") REFERENCES "public"."mst_users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
